### ISSUE TITLE
Braid class is a bit strange

### ISSUE THREAD

**Issue by treeowl** [slpopejoy/fadno-braids#2]
This would be more idiomatic and more generally applicable.

``` haskell
class (Integral b, Monoid ab) => Braid b ab | ab -> b where

    {-# MINIMAL toGens,minIndex,maxIndex,invert #-}

    -- | "Length", number of "steps"/columns/artin generators.
    stepCount :: ab -> Int
    -- | "N", braid group index, number of strands/rows/"i"s.
    strandCount :: ab -> b
    -- | Common format is a series of "steps" of absolute-indexed generators.
    toGens :: ab -> [[Gen b]]
    -- | Minimum index (i) value
    minIndex :: ab -> b
    -- | Maximum index (i) value. Note this means values of (i+1) obtain, per generators.
    maxIndex :: ab -> b
    -- | Invert indices
    invert :: ab -> ab
    -- | convert to single-gen
    toArtin :: ab -> Artin b
    -- | convert to multi-gen
    toMultiGen :: ab -> MultiGen b

    strandCount a = (maxIndex a + 2) - minIndex a

    stepCount = length . toGens -- inefficient

    toArtin = Artin . concat . toGens

    toMultiGen = MultiGen . map gensToStep . toGens

```

**Comment by cartazio** [comment]
at some level, it looks like this is kinda about "polynomials with integer coefficients", right?
from that perspective, maybe 

``` haskell
class (Integral b, Monoid (f b), Functor f) => Braid f b where
```

could be another approach? Zooming out, what algebraic laws should a good instance have?

**Comment by treeowl** [comment]
Functors should usually be strengthened to Applicative or Alternative, not
Monoid.

**Comment by cartazio** [comment]
I suspect thats the wrong direction, because thats not recognizing that what braids are (abstractly)
is a space of polynomials generated by some set of Free symbols (X^i .... ) with coefficients in some integral ring

Ed's algebra lib, while not 1-1 with whats going on here, does have some related modelling ideas for this kinda pattern. 
https://hackage.haskell.org/package/algebra-4.2/docs/Numeric-Algebra-Class.html#t:Algebra

and the illustrative instance being 

``` haskell
Semiring r => Algebra r [a]
```

where there _is_ no applicative structure for the list/containery thing, or at least theres certainly no strong argument for having a functional dependency between `a` and `r`

**Comment by sirlensalot** [comment]
Got rid of the `(* -> *)` kind constraint. This cleaned up the instances (don't need the parens anymore).
Didn't do the fundeps, they break the instances over `(Integral a)`
Left the type argument order the same, to not break my downstream code.
Thanks David!
